name: Sincronização Diária de Dados do Garmin

on:
  # Permite que você rode este workflow manualmente pela aba Actions
  workflow_dispatch:

  # Roda todo dia às 5h da manhã no horário UTC (2h da manhã em Brasília)
  schedule:
    - cron: '0 5 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar o script de sincronização
        env:
          GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
          GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: python sync_garmin_to_gsheet.py